apiVersion: v1
kind: Service
metadata:
  name: mysqlauth-service
  namespace: production-cloud
  labels:
    label: mysqlauth-service
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 32001
      targetPort: 3306
      protocol: TCP
      name: http

  selector:
    name: mysqlauth-selector
