apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mysqlauth-service #Name of service
  name: mysqlauth-deployment #Name of deployment
  namespace: production-cloud

spec:
  template:
    metadata:
      labels:
        name: mysqlauth-selector #Name of selector
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: admin

          image: mysql:latest
          name: mysqlauth-container
          ports:
            - name: mysqlauth-port
              containerPort: 3306
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
