apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: registry-service #Name of service
  name: registry
  namespace: kubeserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: registry
    spec:
      containers:
        - resources:
          name: registry
          image: registry:2
          ports:
            - name: registry-port
              containerPort: 9405
          volumeMounts:
            - mountPath: /var/lib/registry
              name: images
      volumes:
        - name: images
          hostPath:
            path: /root/registry/images
      nodeSelector:
        name: kubeserver-registry
