apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: kubeserver
  labels:
    label: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 32001
      targetPort: 3306
      protocol: TCP
      name: http

  selector:
    name: mysql-selector
