apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mysql-service #Name of service
  name: mysql-deployment #Name of deployment
  namespace: kubeserver

spec:
  template:
    metadata:
      labels:
        name: mysql-selector #Name of selector
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: admin

          image: mysql:latest
          name: mysql-container
          ports:
            - name: mysql-port
              containerPort: 3306
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
